// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Adyn-Cox/CoorsHeavy/internal/auth"

// Layout is the black background / white text shell shared by every page: header
// with softball logo + nav + login state, then page content. Loads HTMX,
// Tailwind, and SortableJS.
func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/layout.templ`, Line: 14, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " · Coors Heavy</title><link rel=\"icon\" href=\"/static/logo.webp\" type=\"image/webp\"><script src=\"https://unpkg.com/htmx.org@2.0.3\"></script><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://cdn.jsdelivr.net/npm/sortablejs@1.15.3/Sortable.min.js\"></script><link rel=\"stylesheet\" href=\"/static/app.css\"></head><body class=\"min-h-screen bg-black text-white\"><header class=\"border-b-2 border-white\"><div class=\"mx-auto flex max-w-4xl items-center justify-between gap-4 px-4 py-3\"><a href=\"/\" class=\"flex items-center gap-3\"><img src=\"/static/logo.webp\" alt=\"Coors Heavy\" class=\"h-14 w-14 object-contain\"> <span class=\"hidden sm:inline text-xl font-black uppercase tracking-widest\">Coors Heavy</span></a><nav class=\"flex items-center gap-4 text-sm font-semibold uppercase tracking-wide\"><a href=\"/lineup\" class=\"hover:underline\">Lineup</a> <a href=\"/schedule\" class=\"hover:underline\">Schedule</a> <a href=\"/stats\" class=\"hover:underline\">Stats</a> <a href=\"/beer\" class=\"hover:underline\">Beer</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if auth.IsAdmin(ctx) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<form method=\"post\" action=\"/logout\"><button type=\"submit\" class=\"border border-white bg-white px-2 py-1 text-black hover:bg-black hover:text-white\">Log out</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"/login\" class=\"border border-white px-2 py-1 hover:bg-white hover:text-black\">Admin</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</nav></div></header><main class=\"mx-auto max-w-4xl px-4 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</main><script>\n\t\t\t\t// Initialise drag-and-drop on any .sortable container (admin lineup).\n\t\t\t\thtmx.onLoad(function (content) {\n\t\t\t\t\tcontent.querySelectorAll('.sortable').forEach(function (el) {\n\t\t\t\t\t\tif (el._sortable) return;\n\t\t\t\t\t\tel._sortable = new Sortable(el, { animation: 150, handle: '.drag-handle' });\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t</script><!-- Song search modal --><div id=\"song-modal\" class=\"hidden fixed inset-0 z-50 flex items-center justify-center\" style=\"background:rgba(0,0,0,0.85)\" onclick=\"if(event.target===this)closeSongModal()\"><div id=\"song-modal-inner\" class=\"w-full max-w-md border-2 border-white bg-black p-6 mx-4\"></div></div><script>\n\t\t\t\tfunction openSongModal() { document.getElementById('song-modal').classList.remove('hidden'); }\n\t\t\t\tfunction closeSongModal() {\n\t\t\t\t\tdocument.getElementById('song-modal').classList.add('hidden');\n\t\t\t\t\tdocument.getElementById('song-modal-inner').innerHTML = '';\n\t\t\t\t}\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
